### ISSUE TITLE
Code Review #2(Wu Sun)

### ISSUE THREAD

**Issue by sunwu555** [CaptainGinyu/RobotFilmmaker#10]
- The Readme file does its job this time, Now I could get a view about all your project. The system diagram and repository description part really helps me better understanding your job, that diagram is elegance! Impressing me a lot about our project.
- It took me some time to realize "Demo" folder is where I should check, again it would be better if there is a readme file in that direction too. However, based on your demo video, your project is getting some function about self tracking now, good work!
- Although I don't have the required equipments to implement this project, but I can image your implement method based on your system diagram. But it's nicer if there are some engineering implement method describing file for our better review.

I love sports filming using my gopro or Mavic, but there are not always somebody else help you filming yourself, hope some day seeing the robot filmmaker open to market!

**Comment by harshilprajapati** [comment]
Thank You.
