### ISSUE TITLE
Code Review #2

### ISSUE THREAD

**Issue by SamiSousa** [CaptainGinyu/RobotFilmmaker#12]
README.md:
 + Much more descriptive and informative than last time. Very professional. Good work here.
 - Although the scripts to run are listed at the bottom of the Readme, as an everyday user I would like a step-by-step instruction guide on how to set up the code base, walking me through it all.
 - I couldn't find "COMBINED-Train1-Mugshots.py" or "COMBINED-Train1-Mugshots.py" in the Demo folder, or in the project directories. Perhaps these names have changed; if so it would be nice to reflect this in the README.

I decided to go through a couple scripts in the Demo folder, since this seemed like the most up-to-date build of your project (correct me if I'm wrong):
Demo_Solo_Training.py:
 - This script has a dependency on a library called "boto3" which I didn't have before reviewing. As a rule, any library dependencies for the project should be listed somewhere so users can set those up. 
 - This script set WEBCAM_PORT to 1, but it says in the comments to set it to 0.
 + Nice job on the comments!
 - Crashes saying "Error: Cannot read s3creds.txt" after capturing my face
 + All the pictures are of my face
Demo_Solo_Tracking.py:
 (!) For my windows machine, I needed to install extra opencv libraries at https://github.com/opencv/opencv_contrib in order to get the "face" module from "cv2". If you were developing on linux and there were no issues I understand this being missed
 - Because of this problem I didn't get to test this script
mosse.py:
 + Nice comment head detailing the usage of this file at a high level
 - Not many comments in the code itself.
 (!) There's a reference to a paper that describes the MOSSE process, but I'm not sure if this is code provided by that paper or code implementing the paper. If this is borrowed code, it would be appropriate to include a link to where you got it or a name of who wrote it.

Overall, I'd say you guys have made incredible progress on this project. Give yourselves a pat on the back, and best of luck on Wednesday at the demo!

**Comment by philyuan** [comment]
MOSSE was taken from openCV examples.  We added some helper functions inside the class but pretty much all the credit goes to their respective authors.  I added some clarifications to credit them.

We redid our file structure and updated the section in the Readme file that includes the purpose for each file.  Hope it's more clear.

We also added software dependencies in the readme file as well per your request.  Thanks for the comments!
