### ISSUE TITLE
Code Review #2 (Siva Tejaswi Irkm)

### ISSUE THREAD

**Issue by SivaTejaswiIrkm** [CaptainGinyu/RobotFilmmaker#13]
1. Updated readme file is amazingly descriptive.
2. The entire GitHub repository is very well categorised and maintained and along with the readme makes it clear to follow.
3. Examples + Tutorials folder is a good way to back up the example code for reference.
4. Readme file however does not explain how to initially set up and run the code, adding that would be helpful.
5. In general, it is preferred to use camelCase for names of functions and capital letters for names of all variables.

Significant improvement from the previous code review. Really looking forward for the robot filmmaker demo. Good luck guys!

**Comment by harshilprajapati** [comment]
Thank You.
