### ISSUE TITLE
[EC601] Nick's Code Review

### ISSUE THREAD

**Issue by nv314961** [CaptainGinyu/RobotFilmmaker#3]
README.md
- Is empty! Contains no information about the project or the purpose of the source code. I know where to find your presentations on Google Drive to get this information, but it would be great if this file had a brief project description and how the files within the repo function.

sandbox.py
- The code itself is formatted OK and easy to read.
- Lack of comments. This particular file doesn't need a ton of comments, but having a few that outline the major functions would help a lot with understanding the code.

/servosTest/servosTest.ino
- Given the name of the file, not sure if this code will end up being implemented in your project. If so, a couple comments here would help too. What motions are the servos performing?

/Training/camshiftdemo.py
- I appreciate the comments provided here. They are brief, selective, and explain well enough what the general process is.
- For lines 29 & 30, perhaps use variables that contain the integer values that correspond with the appropriate keys. At a glance, I'm not sure what key "27" or "60" is.

Thanks for reading guys. Best of luck with the project!

**Comment by harshilprajapati** [comment]
Thank You Nick for your comments. Regarding /Training/camshiftdemo.py its just the code available online that we just wanted to check if it's working separately, we have incorporated that in the main code that is /Training/track.py where we have mentioned the reason for "27" and "60" which basically is the value of escape key and space bar.

**Comment by nv314961** [comment]
@harshilprajapati Thank you for the clarifications!
