### ISSUE TITLE
Code Review (SivaTejaswi Irkm)

### ISSUE THREAD

**Issue by SivaTejaswiIrkm** [CaptainGinyu/RobotFilmmaker#6]
1. It is difficult to understand the project without an updated readme file.
2. cloudtraining.py file contains some code that has been commented. I understand the project is still under development but there is a way to retrieve deleted lines of code from git without having to comment them and keep it in your code. 
3. servosTest.ino is very clearly named and written and is easy to understand.
4. Not very sure how to build the code and see the implementation.

**Comment by philyuan** [comment]
We added some software dependencies to the readme. Thanks for the advice!
