### ISSUE TITLE
Code Review (Sami Shahin)

### ISSUE THREAD

**Issue by SamiSousa** [CaptainGinyu/RobotFilmmaker#7]
Overall, the work here is really nice. Great work!

However, I'm a bit lost since there's not much documentation in terms of Readme files or comments. It would be very beneficial for there to be a document outlining the software architecture, or a high level description of which files do what.

For example, 'servosTest.ino' is a rather straight forward Arduino script. I'm pretty familiar with writing code for Arduino, so I can tell it's a quick and effective script for controlling servos. But I don't know what purpose the script serves at a high level. This problem could be solved with a comprehensive documentation.

Since many files have the word "test" in their name, I'm not sure if those are experiments or part of the current system. If they're test, maybe putting them on another branch would be neater.

Keep up the good work, and good luck going forward!

**Comment by philyuan** [comment]
Descriptions of the purpose of each code file has been added. Thanks for the comments!
