### ISSUE TITLE
Code Review (Wu Sun)

### ISSUE THREAD

**Issue by sunwu555** [CaptainGinyu/RobotFilmmaker#8]

**Comment by sunwu555** [comment]
I checked the sandbox.py and the face track function worked, good job!
However the other part of the code is a little confuse me, here are some of my opinions:
1, I just assumed the "right","left","up","down" string which generate from sandbox.py are the control signals for the robot arm, it would be better if you have some comments inside the code.
2, A readme file could really helps us review your project.
3, Although face track function worked sometimes, more that half of the time it could'n recognize my face, the code still needs to be improved.

**Comment by philyuan** [comment]
Readme file updated, and some clarifiication comments have been aded.

Face tracking is mostly dependent on the training so if you happen to train a picture of your nose (for example mugshots captures nose pictures) then it will mostly detect your nose.  Thanks!
