### ISSUE TITLE
Code Review #2 (Nick VanDeusen)

### ISSUE THREAD

**Issue by nv314961** [CaptainGinyu/RobotFilmmaker#9]
README.md
- Substantially improved since my first code review! Really impressed with this, particularly with the System Diagram.

Repository structure
- Again, overall improvement from last time. I'm assuming the working directory for the project is now contained in the "Demo/" folder. The readme does a fine job at explaining what the core files in this directory do. Perhaps archive / clean up the .py and .xml files in your home directory if they're not being used?

COMBINED-Train1-Mugshots.py
- I appreciate that there are comments throughout that explain the purpose of a function or block of code. Could someone put a comment explaining what size, count, and add are? (lines 10, 12, 13). Also, in line 56, I understand that you specify in the comment before that '27' corresponds to Escape. However, it would be more effective to make a variable ESCAPE = 27 and call ESCAPE instead of 27 in line 56. That way, a user with a different keyboard configuration or wishes to use a different key can do so effectively.
Similiar situation for line 163 in COMBINED-Track.py.

Overall, really impressed with how your GitHub is organized now. Looking forward to seeing your Sprint 4 presentation & demo!

-- Nick VanDeusen

**Comment by philyuan** [comment]
Thanks for the advice! We are definitely going to clean up the loose files. 

size/count/add are removed since we revamped the code.  And we put a comment that 27=ESCAPE since we see now that it could be confusing. Thanks!
